full_feed = {
    "id": "https://watfg.github.io/feedmixer/full/atom.xml",
    "title": "Mixed feed generated by feedmixer",
    "subtitle": "Include full entry",
    "author": {
        "name": "watfg",
        "email": "watfg_81a@outlook.com"
    },
    "href_self": "https://watfg.github.io/feedmixer/full/atom.xml",
    "filepath": "full/atom.xml",
    "lang": "ja"
}

new_feed = {
    "id": "https://watfg.github.io/feedmixer/new/atom.xml",
    "title": "Mixed feed generated by feedmixer",
    "subtitle": "Include only new entry",
    "author": {
        "name": "watfg",
        "email": "watfg_81a@outlook.com"
    },
    "href_self": "https://watfg.github.io/feedmixer/new/atom.xml",
    "filepath": "new/atom.xml",
    "lang": "ja"
}